- name: Config Elk VM with Docker
  hosts: elk
  remote_user: azureuser
  become: true
  tasks:
    #use apt module
    - name: install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present

    #use apt module
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    #use pip module(it will default to pip3)
    - name: Install Docker module
      pip:
        name: docker
        state: present

    #use command module
    - name: Increase virtual memory
      command: sysctl -w vmmax_map_count=262144

    #use sysctl module
    - name: Use More Memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    #use docker_container module
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        #list the ports that Elk runs on
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    #use systemd module
    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
